import { useState, useRef, useEffect } from 'react'
import { encryptMessage, decryptMessage } from '../../utils/crypto'
import {
  generateDHKeyPair,
  computeSharedSecret,
  deriveAesKeyFromSharedSecret,
  bigIntToBytes,
  shortHex,
  GENERATOR,
} from '../../utils/dh'
import {
  generateIdentityKeyPair,
  exportPublicKeyHex,
  signBytes,
  verifyBytes,
  bufferToHex,
  shortHex as sigShortHex,
} from '../../utils/auth'
import './Level4.css'

const STEP_DELAY_MS = 550

function Level4() {
  const [aliceMsgs, setAliceMsgs] = useState([])
  const [bobMsgs, setBobMsgs] = useState([])
  const [eveMsgs, setEveMsgs] = useState([])
  const [input, setInput] = useState('')
  const [sender, setSender] = useState('alice')
  const [status, setStatus] = useState('identities') // 'identities' | 'exchanging' | 'ready' | 'failed'
  const [aliceFingerprint, setAliceFingerprint] = useState('')
  const [bobFingerprint, setBobFingerprint] = useState('')

  const aliceIdentityRef = useRef(null) // long-term ECDSA keypair, generated once
  const bobIdentityRef = useRef(null)
  const keyRef = useRef(null) // derived AES key, per exchange

  const msgId = useRef(1)
  const runIdRef = useRef(0) // guards against a stale run still writing state after "New exchange" or unmount
  const aliceScrollRef = useRef(null)
  const bobScrollRef = useRef(null)
  const eveScrollRef = useRef(null)

  // Long-term identity keys: generated once on mount, NOT regenerated by "New exchange" —
  // they represent identities both parties already trust, independent of any one session.
  // Eve never gets a copy of either private key — she only ever sees what crosses the wire.
  useEffect(() => {
    let cancelled = false
    ;(async () => {
      const alice = await generateIdentityKeyPair()
      const bob = await generateIdentityKeyPair()
      if (cancelled) return
      aliceIdentityRef.current = alice
      bobIdentityRef.current = bob
      setAliceFingerprint(sigShortHex(await exportPublicKeyHex(alice.publicKey)))
      setBobFingerprint(sigShortHex(await exportPublicKeyHex(bob.publicKey)))
      runHandshake()
    })()
    return () => { cancelled = true; runIdRef.current++ } // invalidate any in-flight run on unmount
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    if (aliceScrollRef.current) aliceScrollRef.current.scrollTop = aliceScrollRef.current.scrollHeight
  }, [aliceMsgs])

  useEffect(() => {
    if (bobScrollRef.current) bobScrollRef.current.scrollTop = bobScrollRef.current.scrollHeight
  }, [bobMsgs])

  useEffect(() => {
    if (eveScrollRef.current) eveScrollRef.current.scrollTop = eveScrollRef.current.scrollHeight
  }, [eveMsgs])

  function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms))
  }

  function addAlice(text, type = 'step') {
    setAliceMsgs(prev => [...prev, { id: msgId.current++, type, text }])
  }
  function addBob(text, type = 'step') {
    setBobMsgs(prev => [...prev, { id: msgId.current++, type, text }])
  }
  function addEve(text, type = 'capture') {
    setEveMsgs(prev => [...prev, { id: msgId.current++, type, text }])
  }

  async function runHandshake() {
    const myRun = ++runIdRef.current
    const stale = () => runIdRef.current !== myRun

    setStatus('exchanging')
    setAliceMsgs([])
    setBobMsgs([])
    setEveMsgs([])

    const aliceIdentity = aliceIdentityRef.current
    const bobIdentity = bobIdentityRef.current

    // 1. Agree on public DH parameters
    addAlice(`Agreed public parameters — p (2048-bit prime), g = ${GENERATOR}`)
    addBob(`Agreed public parameters — p (2048-bit prime), g = ${GENERATOR}`)
    addEve(`Intercepted: p (2048-bit), g = ${GENERATOR} — public by design, nothing secret yet`)
    await sleep(STEP_DELAY_MS)
    if (stale()) return

    // 2. Each side generates a fresh temporary DH keypair for this session
    addAlice('Generating ephemeral private value a…')
    addBob('Generating ephemeral private value b…')
    await sleep(STEP_DELAY_MS)
    if (stale()) return

    const alice = generateDHKeyPair()
    const bob = generateDHKeyPair()
    addAlice(`Computing A = g^a mod p = ${shortHex(alice.publicKey)}`)
    addBob(`Computing B = g^b mod p = ${shortHex(bob.publicKey)}`)
    await sleep(STEP_DELAY_MS)
    if (stale()) return

    // 3. Each side signs its own DH public value with its long-term identity key
    addAlice('Signing A with my identity key…')
    addBob('Signing B with my identity key…')
    const aBytes = bigIntToBytes(alice.publicKey)
    const bBytes = bigIntToBytes(bob.publicKey)
    const sigA = await signBytes(aliceIdentity.privateKey, aBytes)
    const sigB = await signBytes(bobIdentity.privateKey, bBytes)
    await sleep(STEP_DELAY_MS)
    if (stale()) return

    // 4. Exchange (public value, signature) pairs over the untrusted network
    addAlice('Sending (A, signature) to Bob →')
    addBob('Sending (B, signature) to Alice →')
    addEve(`Intercepted A = ${shortHex(alice.publicKey, 16)} + sig ${sigShortHex(bufferToHex(sigA), 16)}`)
    addEve(`Intercepted B = ${shortHex(bob.publicKey, 16)} + sig ${sigShortHex(bufferToHex(sigB), 16)}`)
    await sleep(STEP_DELAY_MS)
    if (stale()) return

    // 5. Each side verifies the signature against the sender's known identity public key
    const aliceVerifiedBob = await verifyBytes(bobIdentity.publicKey, sigB, bBytes)
    const bobVerifiedAlice = await verifyBytes(aliceIdentity.publicKey, sigA, aBytes)

    addAlice(
      aliceVerifiedBob
        ? "✓ Verified B's signature against Bob's known identity key"
        : "✕ Signature verification FAILED — rejecting this key"
    )
    addBob(
      bobVerifiedAlice
        ? "✓ Verified A's signature against Alice's known identity key"
        : "✕ Signature verification FAILED — rejecting this key"
    )
    await sleep(STEP_DELAY_MS)
    if (stale()) return

    if (!aliceVerifiedBob || !bobVerifiedAlice) {
      setStatus('failed')
      return
    }

    // 6. After authenticating the source of each public value, compute the shared secret
    const sharedAlice = computeSharedSecret(alice.privateKey, bob.publicKey)
    const sharedBob = computeSharedSecret(bob.privateKey, alice.publicKey)

    addAlice(`Computing s = B^a mod p = ${shortHex(sharedAlice)}`)
    addBob(`Computing s = A^b mod p = ${shortHex(sharedBob)}`)
    addEve('Has p, g, A, B, and both signatures — still cannot derive s without solving the discrete log problem')
    await sleep(STEP_DELAY_MS)
    if (stale()) return

    // 7. Derive the symmetric key from the shared secret
    addAlice('Deriving AES-256 key = SHA-256(s)…')
    addBob('Deriving AES-256 key = SHA-256(s)…')
    const aesKey = await deriveAesKeyFromSharedSecret(sharedAlice)
    if (stale()) return
    keyRef.current = aesKey
    await sleep(400)
    if (stale()) return

    addAlice('Secure, authenticated channel ready — you can chat now.', 'ready-note')
    addBob('Secure, authenticated channel ready — you can chat now.', 'ready-note')
    setStatus('ready')
  }

  async function sendMsg() {
    const text = input.trim()
    if (!text || status !== 'ready') return

    const ts = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    const id = msgId.current++
    const key = keyRef.current

    const { ivHex, ciphertextB64, ciphertextBytes } = await encryptMessage(key, text)
    const decrypted = await decryptMessage(key, ivHex, ciphertextB64)

    const sentMsg = { id, type: 'sent', text }
    const deliveredMsg = { id: id + 0.1, type: 'received', text: decrypted }
    const eveMsg = {
      id: id + 0.2,
      type: 'attacker',
      sender,
      ts,
      ciphertextB64,
      ivHex,
      bytes: ciphertextBytes,
    }

    if (sender === 'alice') {
      setAliceMsgs(prev => [...prev, sentMsg])
      setBobMsgs(prev => [...prev, deliveredMsg])
    } else {
      setBobMsgs(prev => [...prev, sentMsg])
      setAliceMsgs(prev => [...prev, deliveredMsg])
    }

    setEveMsgs(prev => [...prev, eveMsg])
    setInput('')
  }

  function handleKey(e) {
    if (e.key === 'Enter') sendMsg()
  }

  const busy = status === 'exchanging' || status === 'identities'

  return (
    <div className="level4">

      <div className="identity-panel">
        <div className="identity-item">
          <i className="ti ti-shield-check" aria-hidden="true" />
          <span className="identity-label">Alice's identity key</span>
          <code className="identity-value">{aliceFingerprint || 'generating…'}</code>
        </div>
        <div className="identity-item">
          <i className="ti ti-shield-check" aria-hidden="true" />
          <span className="identity-label">Bob's identity key</span>
          <code className="identity-value">{bobFingerprint || 'generating…'}</code>
        </div>
        <span className="identity-caveat">
          Long-term identity private keys known to both parties in advance — Eve never has a copy of either.
        </span>
      </div>

      <div className="handshake-bar">
        <div className="handshake-label">
          <i className="ti ti-arrows-exchange" aria-hidden="true" />
          Authenticated DH key exchange {
            status === 'ready' ? '— complete' :
            status === 'failed' ? '— FAILED (signature invalid)' :
            '— in progress…'
          }
        </div>
        <button className="handshake-redo" onClick={runHandshake} disabled={busy}>
          New exchange
        </button>
      </div>

      <div className="chat-area">

        <div className="chat-col">
          <h3 className="col-heading">Alice</h3>
          <div className="messages" ref={aliceScrollRef}>
            {aliceMsgs.map(m => (
              <div key={m.id} className={`msg ${m.type}`}>{m.text}</div>
            ))}
          </div>
        </div>

        <div className="attacker-col">
          <div className="sniff-indicator">
            <div className="dot" /> Eve (eavesdropping)
          </div>
          <h3 className="col-heading eve">Intercepted</h3>
          <div className="messages" ref={eveScrollRef}>
            {eveMsgs.map(m => {
              if (m.type === 'attacker') {
                return (
                  <div key={m.id} className="msg attacker">
                    [{m.ts}] FROM: {m.sender.toUpperCase()} · {m.bytes}B<br />
                    <span className="cipher-label">IV</span> {m.ivHex}<br />
                    <span className="cipher-label">CT</span> {m.ciphertextB64}
                    <div className="cannot-read">✕ cannot read plaintext</div>
                  </div>
                )
              }
              return <div key={m.id} className="msg capture">{m.text}</div>
            })}
          </div>
        </div>

        <div className="chat-col">
          <h3 className="col-heading">Bob</h3>
          <div className="messages" ref={bobScrollRef}>
            {bobMsgs.map(m => (
              <div key={m.id} className={`msg ${m.type}`}>{m.text}</div>
            ))}
          </div>
        </div>

      </div>

      <div className="input-row">
        <select value={sender} onChange={e => setSender(e.target.value)}>
          <option value="alice">Alice</option>
          <option value="bob">Bob</option>
        </select>
        <input
          type="text"
          value={input}
          onChange={e => setInput(e.target.value)}
          onKeyDown={handleKey}
          placeholder={status === 'ready' ? 'Type a message — encrypted with the authenticated key…' : 'Running authenticated key exchange…'}
          disabled={status !== 'ready'}
        />
        <button onClick={sendMsg} disabled={status !== 'ready'}>Send</button>
      </div>

      <div className="info-panel">
        <h4>What's happening</h4>
        <p>
          Before Alice and Bob trust each other's DH public value, each one is signed with the
          sender's long-term identity public key and verified against a private version of that 
          public key the other side already holds. Eve can watch every bit of this handshake —
          the public values, both signatures, later the ciphertext — but she holds neither identity
          private key, so she can't produce a signature Alice or Bob would accept, and she can't derive
          the shared secret from public values alone.
        </p>
      </div>
    </div>
  )
}

export default Level4